# Site/SEO settings
email: dainius@kacinskas.com
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Dainius Kacinskas
title: Dainius Kacinskas
description: >
url: http://www.kacinskas.com
twitter_username: 
default_img: /assets/images/seo.jpg
social:

  - name: instagram
    url: https://www.instagram.com/itsdainius
  - name: linkedin
    url: https://www.linkedin.com/in/dainiuskacinskas/


# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: 

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: 
mailchimp_input: 

# Author settings
author:
  - name: Dainius Kacinskas
    bio: 
    url: http://kacinskas.com

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 3
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'startDate'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'Dainius Kacinskas'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor
